/**
 * 🤖 useAutoWorkouts Hook
 * Hook para manejar rutinas automáticas basadas en asignaciones de splits
 */

import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { apiRequest } from '@/lib/api';

interface AutoWorkout {
  id: number;
  splitName: string;
  exercises: any[];
  estimatedDuration: number;
  targetMuscleGroups: string[];
  aiConfidenceScore: number;
  generationMetadata: any;
  isAutoGenerated: boolean;
}

interface CacheStatus {
  userId: number;
  totalCached: number;
  nextWeekCached: number;
  oldestCached: string;
  newestCached: string;
  needsGeneration: string[];
}

export function useAutoWorkouts() {
  const queryClient = useQueryClient();

  /**
   * 🎯 Obtener rutina automática para una fecha específica
   */
  const useAutoWorkout = (date?: string) => {
    return useQuery({
      queryKey: ['/api/scientific-workouts/auto-workout', date],
      queryFn: async () => {
        console.log('🤖 [useAutoWorkouts] Fetching auto workout for date:', date);
        
        const params = date ? `?date=${date}` : '';
        const response = await apiRequest('GET', `/api/scientific-workouts/auto-workout${params}`);
        const data = await response.json();
        
        console.log('🤖 [useAutoWorkouts] Auto workout response:', data);
        return data;
      },
      staleTime: 5 * 60 * 1000, // 5 minutos
      cacheTime: 10 * 60 * 1000, // 10 minutos
    });
  };

  /**
   * 🎯 Obtener rutina automática para hoy
   */
  const useTodayAutoWorkout = () => {
    const today = new Date().toISOString().split('T')[0];
    return useAutoWorkout(today);
  };

  /**
   * 📊 Obtener estado del cache
   */
  const useCacheStatus = () => {
    return useQuery({
      queryKey: ['/api/scientific-workouts/cache-status'],
      queryFn: async () => {
        console.log('📊 [useAutoWorkouts] Fetching cache status...');
        
        const response = await apiRequest('GET', '/api/scientific-workouts/cache-status');
        const data = await response.json();
        
        console.log('📊 [useAutoWorkouts] Cache status:', data);
        return data;
      },
      staleTime: 2 * 60 * 1000, // 2 minutos
      cacheTime: 5 * 60 * 1000, // 5 minutos
    });
  };

  /**
   * 🔄 Regenerar cache de rutinas
   */
  const useRegenerateCache = () => {
    return useMutation({
      mutationFn: async (daysAhead: number = 7) => {
        console.log('🔄 [useAutoWorkouts] Regenerating cache for', daysAhead, 'days ahead...');
        
        const response = await apiRequest('POST', '/api/scientific-workouts/regenerate-cache', {
          daysAhead
        });
        
        const data = await response.json();
        console.log('🔄 [useAutoWorkouts] Cache regenerated:', data);
        return data;
      },
      onSuccess: () => {
        // Invalidar queries relacionadas
        queryClient.invalidateQueries({ queryKey: ['/api/scientific-workouts/cache-status'] });
        queryClient.invalidateQueries({ queryKey: ['/api/scientific-workouts/auto-workout'] });
        console.log('✅ [useAutoWorkouts] Cache queries invalidated');
      },
      onError: (error) => {
        console.error('❌ [useAutoWorkouts] Error regenerating cache:', error);
      }
    });
  };

  /**
   * 🗓️ Obtener rutinas para múltiples fechas
   */
  const useWeeklyAutoWorkouts = (startDate: string, days: number = 7) => {
    return useQuery({
      queryKey: ['/api/scientific-workouts/weekly-auto-workouts', startDate, days],
      queryFn: async () => {
        console.log('🗓️ [useAutoWorkouts] Fetching weekly workouts from:', startDate, 'for', days, 'days');
        
        const workouts: { [date: string]: AutoWorkout | null } = {};
        const promises = [];
        
        for (let i = 0; i < days; i++) {
          const date = new Date(startDate);
          date.setDate(date.getDate() + i);
          const dateStr = date.toISOString().split('T')[0];
          
          promises.push(
            apiRequest('GET', `/api/scientific-workouts/auto-workout?date=${dateStr}`)
              .then(response => response.json())
              .then(data => ({ date: dateStr, workout: data.workout }))
              .catch(error => {
                console.error(`❌ [useAutoWorkouts] Error fetching workout for ${dateStr}:`, error);
                return { date: dateStr, workout: null };
              })
          );
        }
        
        const results = await Promise.all(promises);
        results.forEach(({ date, workout }) => {
          workouts[date] = workout;
        });
        
        console.log('🗓️ [useAutoWorkouts] Weekly workouts fetched:', workouts);
        return workouts;
      },
      staleTime: 5 * 60 * 1000, // 5 minutos
      cacheTime: 10 * 60 * 1000, // 10 minutos
    });
  };

  /**
   * 🎯 Marcar rutina como completada
   */
  const useCompleteWorkout = () => {
    return useMutation({
      mutationFn: async ({ workoutId, date }: { workoutId: number; date: string }) => {
        console.log('✅ [useAutoWorkouts] Marking workout as completed:', workoutId, date);
        
        // Aquí se podría llamar a un endpoint específico para marcar como completada
        // Por ahora, simplemente invalidamos las queries
        return { workoutId, date };
      },
      onSuccess: (data) => {
        // Invalidar queries relacionadas
        queryClient.invalidateQueries({ queryKey: ['/api/scientific-workouts/auto-workout', data.date] });
        queryClient.invalidateQueries({ queryKey: ['/api/scientific-workouts/cache-status'] });
        console.log('✅ [useAutoWorkouts] Workout completion queries invalidated');
      },
      onError: (error) => {
        console.error('❌ [useAutoWorkouts] Error completing workout:', error);
      }
    });
  };

  /**
   * 🔄 Refrescar rutinas automáticas
   */
  const refreshAutoWorkouts = () => {
    console.log('🔄 [useAutoWorkouts] Refreshing auto workouts...');
    queryClient.invalidateQueries({ queryKey: ['/api/scientific-workouts/auto-workout'] });
    queryClient.invalidateQueries({ queryKey: ['/api/scientific-workouts/cache-status'] });
  };

  /**
   * 🎯 Verificar si hay rutina para hoy
   */
  const useHasTodayWorkout = () => {
    const { data: todayWorkout, isLoading } = useTodayAutoWorkout();
    
    return {
      hasWorkout: !isLoading && todayWorkout?.success && todayWorkout?.workout && !todayWorkout?.isRestDay,
      isRestDay: !isLoading && todayWorkout?.isRestDay,
      workout: todayWorkout?.workout,
      isLoading
    };
  };

  /**
   * 📊 Obtener estadísticas de rutinas automáticas
   */
  const useAutoWorkoutStats = () => {
    const { data: cacheStatus } = useCacheStatus();
    
    return {
      totalCached: cacheStatus?.cacheStatus?.totalCached || 0,
      nextWeekCached: cacheStatus?.cacheStatus?.nextWeekCached || 0,
      needsGeneration: cacheStatus?.cacheStatus?.needsGeneration || [],
      isHealthy: (cacheStatus?.cacheStatus?.nextWeekCached || 0) >= 3 // Al menos 3 días en cache
    };
  };

  return {
    // Queries
    useAutoWorkout,
    useTodayAutoWorkout,
    useCacheStatus,
    useWeeklyAutoWorkouts,
    useHasTodayWorkout,
    useAutoWorkoutStats,
    
    // Mutations
    useRegenerateCache,
    useCompleteWorkout,
    
    // Utils
    refreshAutoWorkouts
  };
}

export default useAutoWorkouts;
